### ISSUE TITLE
[API] - All issues in API folder

### ISSUE THREAD

**Issue by mazipan** [vuejs-id/docs#101]
File Markdown: [https://github.com/vuejs-id/docs/blob/master/src/v2/api/index.md](here)

- [x] Global Config (#102)
- [x] Global API (#103)
- [x] Options / Data (#104)
- [x] Options / DOM (#105)
- [x] Options / Lifecycle Hooks (#106)
- [x] Options / Assets (#107)
- [x] Options / Composition (#108)
- [x] Options / Misc (#109)
- [x] Instance Properties (#110)
- [x] Instance Methods / Data (#111)
- [x] Instance Methods / Events (#112)
- [x] Instance Methods / Lifecycle (#113)
- [x] Directives (#114)
- [x] Special Attributes (#115)
- [x] Built-In Components (#116)
- [x] VNode Interface & Server-Side Rendering (#117) - **CLOSED**

Mas @nusendra dan mas @mandaputtra ini issue untuk tracking folder `api` ya.
Nanti kita akan bikin issue per masing-masing section ini.
